---
- name: Restart elk service on ELK Cluster 
  hosts: elk
  sudo: true
  remote_user: fldengr

  tasks:
  - name: stop the elk compose file
    command: docker-compose -f /arris/compose/elk-compose.yml stop
    async: 60
    poll: 10   
     
  - name: rm elk 
    command: docker-compose -f /arris/compose/elk-compose.yml rm --force
    async: 60
    poll: 10   
     
  - name: start the compose file on first host
    command: docker-compose -f /arris/compose/elk-compose.yml up -d
    when: inventory_hostname  == "{{ play_hosts[0] }}"
  - wait_for: timeout=10
    
  - name: start the compose file on second host
    command: docker-compose -f /arris/compose/elk-compose.yml up -d
    when: inventory_hostname  == "{{ play_hosts[1] }}"
  - wait_for: timeout=10
  
  - name: start the compose file on third host
    command: docker-compose -f /arris/compose/elk-compose.yml up -d
    when: inventory_hostname  == "{{ play_hosts[2] }}"
  - wait_for: timeout=10      
